In [ ]:
from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Read the dataset
df = pd.read_csv("/content/drive/MyDrive/U.S._Chronic_Disease_Indicators.csv")

# Display first 5 rows
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,TopicID,QuestionID,ResponseID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2020,2020,US,United States,BRFSS,Health Status,Recent activity limitation among adults,NaN,Number,Age-adjusted Mean,...,HEA,HEA04,NaN,AGEADJMEAN,SEX,SEXF,NaN,NaN,NaN,NaN
1,2015,2019,AR,Arkansas,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,SEX,SEXM,NaN,NaN,NaN,NaN
2,2015,2019,CA,California,US Cancer DVT,Cancer,"Cervical cancer mortality among all females, u...",NaN,Number,Number,...,CAN,CAN03,NaN,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2015,2019,CO,Colorado,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,RACE,HIS,NaN,NaN,NaN,NaN
4,2015,2019,GA,Georgia,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...",NaN,Number,Number,...,CAN,CAN05,NaN,NMBR,RACE,WHT,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'Response', 'DataValueUnit', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DataValueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'StratificationCategory3', 'Stratification3',
       'Geolocation', 'LocationID', 'TopicID', 'QuestionID', 'ResponseID',
       'DataValueTypeID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

In [ ]:
df.dtypes

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
Response                     float64
DataValueUnit                 object
DataValueType                 object
DataValue                    float64
DataValueAlt                 float64
DataValueFootnoteSymbol       object
DataValueFootnote             object
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
StratificationCategory2      float64
Stratification2              float64
StratificationCategory3      float64
Stratification3              float64
Geolocation                   object
LocationID                     int64
TopicID                       object
QuestionID                    object
ResponseID                   float64
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
StratificationCategoryID2    float64
StratificationID2            float64
StratificationCategoryID3    float64
StratificationID3            float64
dtype: object

In [ ]:
df.describe()

,YearStart,YearEnd,Response,DataValue,DataValueAlt,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,LocationID,ResponseID,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
count,309215.000000,309215.000000,0.0,2.091960e+05,2.091960e+05,188885.000000,188890.000000,0.0,0.0,0.0,0.0,309215.000000,0.0,0.0,0.0,0.0,0.0
mean,2020.012195,2020.288540,NaN,6.943569e+02,7.356701e+02,36.825051,46.030554,NaN,NaN,NaN,NaN,31.208693,NaN,NaN,NaN,NaN,NaN
std,1.530835,1.068591,NaN,1.620341e+04,1.834715e+04,65.025590,69.995643,NaN,NaN,NaN,NaN,17.798773,NaN,NaN,NaN,NaN,NaN
min,2015.000000,2019.000000,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN
25%,2019.000000,2019.000000,NaN,1.240000e+01,1.240000e+01,9.100000,14.000000,NaN,NaN,NaN,NaN,17.000000,NaN,NaN,NaN,NaN,NaN
50%,2020.000000,2020.000000,NaN,2.700000e+01,2.700000e+01,19.500000,29.200000,NaN,NaN,NaN,NaN,31.000000,NaN,NaN,NaN,NaN,NaN
75%,2021.000000,2021.000000,NaN,5.780000e+01,5.780000e+01,40.300000,54.300000,NaN,NaN,NaN,NaN,45.000000,NaN,NaN,NaN,NaN,NaN
max,2022.000000,2022.000000,NaN,2.925456e+06,2.925456e+06,1427.000000,1485.900000,NaN,NaN,NaN,NaN,78.000000,NaN,NaN,NaN,NaN,NaN

In [ ]:
#QN.2 Chceking for missing values
df.isnull().sum()

YearStart                         0
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
DataSource                        0
Topic                             0
Question                          0
Response                     309215
DataValueUnit                     0
DataValueType                     0
DataValue                    100019
DataValueAlt                 100019
DataValueFootnoteSymbol      207499
DataValueFootnote            207499
LowConfidenceLimit           120330
HighConfidenceLimit          120325
StratificationCategory1           0
Stratification1                   0
StratificationCategory2      309215
Stratification2              309215
StratificationCategory3      309215
Stratification3              309215
Geolocation                    5763
LocationID                        0
TopicID                           0
QuestionID                        0
ResponseID                   309215
DataValueTypeID                   0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2    309215
StratificationID2            309215
StratificationCategoryID3    309215
StratificationID3            309215
dtype: int64

In [ ]:
df_small = df[["YearStart", "YearEnd", "LocationAbbr","DataSource", "Topic", "Question","Response", "LowConfidenceLimit","HighConfidenceLimit", "StratificationCategoryID1","StratificationID1"]]
df_small.head(10)

,YearStart,YearEnd,LocationAbbr,DataSource,Topic,Question,Response,LowConfidenceLimit,HighConfidenceLimit,StratificationCategoryID1,StratificationID1
0,2020,2020,US,BRFSS,Health Status,Recent activity limitation among adults,NaN,2.8,2.9,SEX,SEXF
1,2015,2019,AR,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,NaN,NaN,SEX,SEXM
2,2015,2019,CA,US Cancer DVT,Cancer,"Cervical cancer mortality among all females, u...",NaN,NaN,NaN,OVERALL,OVR
3,2015,2019,CO,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,NaN,NaN,RACE,HIS
4,2015,2019,GA,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...",NaN,NaN,NaN,RACE,WHT
5,2015,2019,KS,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,NaN,NaN,SEX,SEXM
6,2015,2019,ME,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,NaN,NaN,OVERALL,OVR
7,2015,2019,NJ,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,NaN,NaN,RACE,HIS
8,2015,2019,NY,US Cancer DVT,Cancer,"Breast cancer mortality among all females, und...",NaN,NaN,NaN,SEX,SEXF
9,2015,2019,OR,US Cancer DVT,Cancer,"Breast cancer mortality among all females, und...",NaN,NaN,NaN,OVERALL,OVR

In [ ]:
df_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309215 entries, 0 to 309214
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   YearStart                  309215 non-null  int64
 1   YearEnd                    309215 non-null  int64
 2   LocationAbbr               309215 non-null  object
 3   DataSource                 309215 non-null  object
 4   Topic                      309215 non-null  object
 5   Question                   309215 non-null  object
 6   Response                   0 non-null       float64
 7   LowConfidenceLimit         188885 non-null  float64
 8   HighConfidenceLimit        188890 non-null  float64
 9   StratificationCategoryID1  309215 non-null  object
 10  StratificationID1          309215 non-null  object
dtypes: float64(3), int64(2), object(6)
memory usage: 26.0+ MB